# Generated by Django 6.0.5 on 2026-06-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Laptops', 'Laptops'), ('Wearables', 'Wearables'), ('Fashion', 'Fashion')], default='Electronics', max_length=20),
        ),
    ]
