# Generated by Django 6.0.5 on 2026-06-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Laptops', 'Laptops'), ('Wearables', 'Wearables'), ('Fashion', 'Fashion')], default='Electronics', max_length=20, null=True),
        ),
    ]
